[package]
name = "langgraph"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
async-trait = { workspace = true }
downcast-rs = { workspace = true }
variadics_please = "1.1"
async-stream = { workspace = true }
futures = "0.3"
tracing = { workspace = true }
langgraph_macro = { path = "./macro" }

[dependencies.tokio]
version = "1"
features = ["macros", "rt", "sync"]

[dependencies.tokio-stream]
version = "0.1"
features = ["sync"]


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(docsrs_dep)'] }
