[package]
name = "langgraph"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
async-trait = { workspace = true }
downcast-rs = { workspace = true }

langgraph_macro = { path = "./macro" }
